### ISSUE TITLE
大佬请问第一步的vim .env后进入的是一个空文件正常吗？

### ISSUE THREAD

**Issue by CosmoWood** [Elegybackup/clash-for-linux-backup#1]
在这里自行添加了CLASH_URL=订阅地址的条目，但是执行第二步显示CLASH_URL为空或没有设置。
因为服务器无法访问github所以是自行下载项目后解压，对这个有影响吗

**Comment by Elegybackup** [comment]
仓库文件没有上传完整，现在已经补齐了，这几天一直在收集剩余的文件，重新git一下，感谢理解
