### ISSUE TITLE
开启了代理但是没连接

### ISSUE THREAD

**Issue by FFF-420** [Elegybackup/clash-for-linux-backup#10]
![图片](https://github.com/Elegybackup/clash-for-linux-backup/assets/64009449/9b7ac1e1-5dd2-4522-bbd3-45ddd3c3ea2e)

**Comment by Elegycloud** [comment]
看看能不能ping通海外站

**Comment by FFF-420** [comment]
> 看看能不能ping通海外站

ping不通
![图片](https://github.com/Elegybackup/clash-for-linux-backup/assets/64009449/ed6152bd-da01-4688-8a22-4acb9a84791a)

**Comment by FFF-420** [comment]
> > 看看能不能ping通海外站
> 
> ping不通 ![图片](https://private-user-images.githubusercontent.com/64009449/285815940-ed6152bd-da01-4688-8a22-4acb9a84791a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzk1OTMsIm5iZiI6MTcwMTA3OTI5MywicGF0aCI6Ii82NDAwOTQ0OS8yODU4MTU5NDAtZWQ2MTUyYmQtZGEwMS00Njg4LThhMjItNGFjYjlhODQ3OTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDEwMDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MzY4YTJlZTlmZjc0YTllYjg3OGNiM2Y4NGRlZjVkYWM5YTk0N2QxM2MzOTFiMThhMWE0NTQzMWM0YzBiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wMBG0rdIC4NH2qOIZi4RcCPHFy-3NSB0Fc_B1VC5B9w)



> 看看能不能ping通海外站
代理里面节点都有，就是连接栏里面啥也没有

**Comment by Elegycloud** [comment]
去网络设置手动设置代理
然后再去试试看，一般情况下有可视化面板的系统都要去网络设置手动设置代理
就比如kali linux

**Comment by heyuqiao** [comment]
可以在网络设置里设置代理，我是这么解决的https://blog.csdn.net/weixin_40617109/article/details/120388145?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522170115632716800188544165%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fblog.%2522%257D&request_id=170115632716800188544165&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_ecpm_v1~rank_v31_ecpm-1-120388145-null-null.nonecase&utm_term=ubantu%E7%BD%91%E7%BB%9C%E8%AE%BE%E7%BD%AE%E6%89%8B%E5%8A%A8%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86&spm=1018.2226.3001.4450

**Comment by FFF-420** [comment]
> 可以在网络设置里设置代理，我是这么解决的https://blog.csdn.net/weixin_40617109/article/details/120388145?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522170115632716800188544165%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fblog.%2522%257D&request_id=170115632716800188544165&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_ecpm_v1~rank_v31_ecpm-1-120388145-null-null.nonecase&utm_term=ubantu%E7%BD%91%E7%BB%9C%E8%AE%BE%E7%BD%AE%E6%89%8B%E5%8A%A8%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86&spm=1018.2226.3001.4450

这个设置ip是设置自己电脑的ip吗
