### ISSUE TITLE
netstat -tln | grep -E '9090|789.' 无显示

### ISSUE THREAD

**Issue by zhangzhuoran997997** [Elegybackup/clash-for-linux-backup#11]
netstat -tln | grep -E '9090|789.' 之前步骤一切正常
但 netstat -tln | grep -E '9090|789.' 命令无显示，同时ping不通外网

**Comment by Elegycloud** [comment]
有可视化面板吗【指的是系统桌面】
有的话去网络设置手动设置代理
没有的话root用户在终端设置好环境变量后输入proxy_on后检查代理是否设置成功
