### ISSUE TITLE
有一个不知道算不算bug的东西

### ISSUE THREAD

**Issue by ChangXinze** [Elegybackup/clash-for-linux-backup#13]
我用ubuntu20.04 的时候，如果没有安装curl（但是有wget）它不会往下执行start.sh，而是直接报：clash订阅地址不可访问
这个应该是启动脚本的判断有点问题
![image](https://github.com/Elegybackup/clash-for-linux-backup/assets/129141287/64ffd659-b5de-4b35-a0f0-0338965e18c2)

**Comment by Elegycloud** [comment]
必须要安装curl，因为可以获取到机场的config.yml
