### ISSUE TITLE
netstat -tln | grep -E '9090|789.' 没有显示端口开放

### ISSUE THREAD

**Issue by geonoon** [Elegybackup/clash-for-linux-backup#15]
用不了！！！

#netstat -tln | grep -E '9090|789.'
返回空，没有端口开放启用
所以就无法连接到代理的7890端口上网。

请帮助解决此问题，谢谢！！！

**Comment by Gmorning730** [comment]
大佬，我也是这个问题，tcp不开，网上查了查怎么开放端口，每次这个指令只显示tcp6，是这样的
![IMG_20231212_163626](https://github.com/Elegybackup/clash-for-linux-backup/assets/87710189/ee114b5b-f506-449d-bbe0-0f98b4cc11df)
呜呜这改咋解决，查了一下午了还是不行

**Comment by Elegybackup** [comment]
> 大佬，我也是这个问题，tcp不开，网上查了查怎么开放端口，每次这个指令只显示tcp6，是这样的 ![IMG_20231212_163626](https://private-user-images.githubusercontent.com/87710189/289795610-ee114b5b-f506-449d-bbe0-0f98b4cc11df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzU2MjgsIm5iZiI6MTcwMjM3NTMyOCwicGF0aCI6Ii84NzcxMDE4OS8yODk3OTU2MTAtZWUxMTRiNWItZjUwNi00NDlkLWJiZTAtMGY5OGI0Y2MxMWRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYjc0MWMxOWExNTI5MTViZTU1ZjAyOWUzNGM0MWU5ODczZGU2NTlhMjU5ZmVhMTllNzkwOWZhZWI2NTVmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTjD59pi-DuCn7xad3NuwtpA5E3II6v-QxAw4k-CXww) 呜呜这改咋解决，查了一下午了还是不行

要学会仔细看README，部分桌面端要关闭系统代理（没用）然后去浏览器设置代理，系统代理不一定有用，如果想要系统代理可以尝试修改项目中的clash.sh文件里面的ip换成127.0.0.1

**Comment by Gmorning730** [comment]
嗯好，谢谢我自己看了一遍，浏览器里也设置了代理，但是还是同样的问题😭走投无路了

**Comment by zzyouyou** [comment]
有人解决了嘛？

**Comment by AdmsLCW** [comment]
我是把防火墙关闭了，在系统中手动代理设置http、https、socks，在浏览器中设置跟随系统代理。最后确认把之前的都关闭了，重新开启就可以了。

**Comment by AdmsLCW** [comment]
还不行 换个url
