### ISSUE TITLE
关于dashboard的一些问题

### ISSUE THREAD

**Issue by XuecWu** [Elegybackup/clash-for-linux-backup#18]
作者您好，有一些问题想询问下您：
1. 我在服务器上部署之后，由于是命令行操作，无法在服务器的浏览器中进行操作；
2. 因此，我们将服务器上的地址进行了windows的端口映射，映射出来的链接为http://127.0.0.1:9090/ui/。
3. 在chrome中对该地址进行访问后，我得到的界面为
![image](https://github.com/Elegybackup/clash-for-linux-backup/assets/75833531/f2facc22-23b1-49f2-b3fd-c18914d23a37)
4. 此时，这里的API Base URL我将http://127.0.0.1:9090以及http://<服务器IP>:9090都尝试了下，并且按照要求输入了Secret，并且点击了Add，之后又点击了下面的**http://127.0.0.1:9090**，但是点击之后，我只能看到那个dashboard闪烁了一下，然而我并进不去。
因此，想请教下您，谢谢！
此外，还有一个问题，我先前尝试了使用bash scripts/clash_proxy-selector.sh，但是在选择节点的时候，我得到的输出为：
![image](https://github.com/Elegybackup/clash-for-linux-backup/assets/75833531/50c9bdc7-d412-443c-96c5-bc952cfb56ea)
这是怎么回事？又该如何处理？
谢谢！

**Comment by Elegybackup** [comment]
1.面板进不去可以是因为IP要输入http://外网IP:9090，内网则输入http://127.0.0.1:9090，然后再输入KEY
2.脚本有问题，没时间修
