### ISSUE TITLE
centos 问题

### ISSUE THREAD

**Issue by lemna7** [Elegybackup/clash-for-linux-backup#19]
![image](https://github.com/Elegybackup/clash-for-linux-backup/assets/125271764/95f538b6-eee8-435c-9c7d-2dda8dd02301)
我已修改了 .env 中的 clash_url。

**Comment by lemna7** [comment]
我把文件都转为 LF 可以了。

**Comment by Elegybackup** [comment]
centos有点问题，可以尝试修改脚本看看
