### ISSUE TITLE
启动成功后并没有代理

### ISSUE THREAD

**Issue by Yeqinsiyu** [Elegybackup/clash-for-linux-backup#2]
输入 netstat -tln | grep -E '9090|789.'后显示的
tcp6       0      0 :::7890                 :::*                    LISTEN     
tcp6       0      0 :::7891                 :::*                    LISTEN     
tcp6       0      0 :::7892                 :::*                    LISTEN     
tcp6       0      0 :::9090                 :::*                    LISTEN     

在bash页面上也没有监控到流量

**Comment by Elegycloud** [comment]
在clash的目录添加好环境变量后输入proxy_on

**Comment by Elegycloud** [comment]
若无法使用，请提供相关截图！

**Comment by fengxiaojie** [comment]
![image](https://github.com/Elegybackup/clash-for-linux-backup/assets/11309594/95a3c47c-e128-4df1-9074-b1995b7456c8)
一切都成功了，无法访问9090端口网页，也无法访问代理

**Comment by fengxiaojie** [comment]
我在虚拟机上还有云服务器上都试过了都不行，不知道问题出在哪

**Comment by Elegycloud** [comment]
> 我在虚拟机上还有云服务器上都试过了都不行，不知道问题出在哪

检查端口是否开放，开放7890，7891，9090端口之后输入proxy_on

**Comment by Elegycloud** [comment]
若无法使用，请提供相关截图，我会为您解答

**Comment by xinxingi** [comment]
已测试，可用。 拉了个其他github项目，跟你这个仓库代码八九不离十，就是起不来。换成你这个一下就起来了。但相对linux进行全局代理怎么搞啊 不仅仅是http+https。

**Comment by Elegycloud** [comment]
> 已测试，可用。 拉了个其他github项目，跟你这个仓库代码八九不离十，就是起不来。换成你这个一下就起来了。但相对linux进行全局代理怎么搞啊 不仅仅是http+https。

因为我这个是作者跑路的最后一个版本

**Comment by Elegycloud** [comment]
> 已测试，可用。 拉了个其他github项目，跟你这个仓库代码八九不离十，就是起不来。换成你这个一下就起来了。但相对linux进行全局代理怎么搞啊 不仅仅是http+https。

还有就是其他的clash for linux都有缺陷，我这个是基于原作者的仓库进行修复后发出来的，其他的要么没有.env，要么没有配置文件
