### ISSUE TITLE
Clash Dashboard

### ISSUE THREAD

**Issue by liangqw995** [Elegybackup/clash-for-linux-backup#3]
请问有Clash Dashboard的详细用法嘛，Label（Opentional）以及Add的用法，我无法登陆，谢谢

**Comment by MisterBowie** [comment]
me too

**Comment by MisterBowie** [comment]
将 .env 的CLASH_SCRE...的值固定就好了

**Comment by liangqw995** [comment]
那clash_proxy-selector.sh这个怎么换节点，输入数字显示不对

**Comment by Elegybackup** [comment]
部分用户无法通过浏览器使用 Clash Dashboard 进行节点选择、代理模式修改等操作，为了方便用户可以在Linux终端进行操作，下面提供了一个功能简单的脚本以便用户可以临时通过终端界面进行配置。

脚本存放位置：scripts/clash_proxy-selector.sh

注意：

使用脚本前，需要修改脚本中的 Secret 变量值为上述启动脚本输出的值，或者与 .env 文件中定义的 CLASH_SECRET 变量值保持一致。
