### ISSUE TITLE
没有管理员权限

### ISSUE THREAD

**Issue by ljhOfGithub** [Elegybackup/clash-for-linux-backup#5]
你好！我看到网络上有一些教程用的版本是没有用sudo的，比如：
https://zhyq118.com/2023/02/07/clash-for-linux-%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95/
请问这个版本的release保存了吗

**Comment by Elegybackup** [comment]
？？？这个没有使用sudo是因为登录账户使用了root-
