### ISSUE TITLE
代理服务正常启动，但是无法成功链接代理服务

### ISSUE THREAD

**Issue by VBPush** [Elegybackup/clash-for-linux-backup#6]
我使用普通用户和ROOT用户安装了clash,并且进行相应配置，成功运行了clash服务
但是不知道为什么，仍然没办法链接代理服务，在Clash Dashboard中我设置了代理节点、开启全局代理、关闭局域网连接等操作
但是仍然链接失败，如下图所示：

同时为了防止是因为端口的问题，我还关闭了防火墙：ufw disable这个命令，使用 ufw status 这个命令查询为inactive

![image](https://github.com/Elegybackup/clash-for-linux-backup/assets/140361823/72da3873-9ac8-4c6e-9234-05d88bff1fb1)

但是他就是链接不上，测试的时候我以访问Google为目标，一直不行，Dashboard的线也是平的

**Comment by Elegycloud** [comment]
设置环境变量，更换线路，如果还是不行重装，安装文档来操作

**Comment by VBPush** [comment]
> 设置环境变量，更换线路，如果仍无法重装，安装文档来操作

还是不行，不知道哪里出问题了，我上面发的那个图9090端口和教程的显示不一样，没有127.0.0.1，可能是因为这个原因吗

**Comment by Andy-Mielk** [comment]
我也遇到了同样的问题，请问楼主解决了吗？

**Comment by Elegycloud** [comment]
kali要去浏览器设置代理，直接设置系统代理没用

**Comment by Leeebaba** [comment]
我的也有问题，clash开局域网的端口，kali死活不走那个端口，流量出不来
