### ISSUE TITLE
无法选择节点

### ISSUE THREAD

**Issue by heroanddream-2** [Elegybackup/clash-for-linux-backup#7]
![微信截图_20231125135431](https://github.com/Elegybackup/clash-for-linux-backup/assets/99738498/df6c975c-365c-4efa-9eba-89943162753e)

**Comment by Elegycloud** [comment]
IP:9090

**Comment by Elegycloud** [comment]
进入网页可视化面板

**Comment by zhoujunlingla** [comment]
输入127.0.0.1:9090/ui之后，依旧无法进入可视化界面

**Comment by Elegycloud** [comment]
开放端口，若无法开放直接关防火墙

**Comment by Elegycloud** [comment]
要开放的端口：9090，7890，7891

**Comment by mingouuu** [comment]
> 要开放的端口：9090，7890，7891

我是在ubuntu上进行部署，确认了iptables和ufw都已经全开放这三个端口但是仍然无法进行外部访问。请问这是什么原因呢？

**Comment by Leee-ZH** [comment]
遇到了相同的问题。可以正常生成config.yaml，订阅地址也正常但是无法选择。进入可视化界面之后无法选择进入

**Comment by Elegycloud** [comment]
> > 要开放的端口：9090，7890，7891
> 
> 我是在ubuntu上进行部署，确认了iptables和ufw都已经全开放这三个端口但是仍然无法进行外部访问。请问这是什么原因呢？

防火墙全部关闭试试看

**Comment by Leee-ZH** [comment]
是用的本地网络的服务器 没有图形化界面所以没法链接127.0.0.1：9090/ui
使用局域网ip可以打开但是无法使用
![1701167279412](https://github.com/Elegybackup/clash-for-linux-backup/assets/14823372/e5583c5f-cfa9-4d2a-87fc-15deb6e3d232)

![1701167683772](https://github.com/Elegybackup/clash-for-linux-backup/assets/14823372/563bd0b8-b8f8-415d-a5d5-24456799eca0)

**Comment by mingouuu** [comment]
> > 要开放的端口：9090，7890，7891
> 
> 我是在ubuntu上进行部署，确认了iptables和ufw都已经全开放这三个端口但是仍然无法进行外部访问。请问这是什么原因呢？

哦哈哈是粗心的问题……忘了在管理平台的安全组设置9090端口入站准入规则

**Comment by koalaaaaaaaaa** [comment]
> ![微信截图_20231125135431](https://private-user-images.githubusercontent.com/99738498/285568159-df6c975c-365c-4efa-9eba-89943162753e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzM1ODMsIm5iZiI6MTcwODI3MzI4MywicGF0aCI6Ii85OTczODQ5OC8yODU1NjgxNTktZGY2Yzk3NWMtMzY1Yy00ZWZhLTllYmEtODk5NDMxNjI3NTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE2MjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxN2Q2MmUxYTBhNTA2ZjNiN2U2MDA2OTJjODZkODUzMDY0N2RkOGIwZTA1ZTE0NDAzY2Q0ZDg2OTRhZGI5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ocmARXdKUJibwzFjFAT9XNv9WEHw-CBosD3mFnZRoF0)

@heroanddream-2 请问你有解决无法选择代理节点的问题了吗？
