### ISSUE TITLE
订阅地址无法访问

### ISSUE THREAD

**Issue by ArthurRyan0803** [Elegybackup/clash-for-linux-backup#8]
windows 上的clash 客户端能用这个订阅地址

**Comment by Elegycloud** [comment]
检查.env是否输入正确，检查服务器网络，检查服务器下载是否正常

**Comment by mingouuu** [comment]
是否检查过curl已安装？

sudo apt install curl

**Comment by yycxx** [comment]
@Elegycloud 我发现一个离谱的事情，描述如下：
【现象】订阅失败
【排查】：
1. 已经检查curl命令已安装
2. 已经确保网络没有问题
3. 我看到shell脚本里实际上是采用curl去下载的，我在linux电脑上尝试了一下，报错：{"message":"token error"}
【定位】：大概可以定位到是我的url问题，所以我后续又进行了一些操作，导致我对这个问题描述：比较离谱
【后续】：
1. 我在我的linux机器上采用同一个url，访问token error
2. 我在我的Windows电脑上采用同一个url，curl返回竟然是正确的？！
3. 不信邪，所以我在我的个人手机上采用同一个手机又进行了一次配置拉取，也是正常的。
【问】：同一个链接是否还会对设备进行上限设置？

**Comment by Elegybackup** [comment]
> 我发现一个离谱的事情，描述如下： 【现象】订阅失败 【排查】：
> 
> 1. 已经检查curl命令已安装
> 2. 已经确保网络没有问题
> 3. 我看到shell脚本里实际上是采用curl去下载的，我在linux电脑上尝试了一下，报错：{“message”：“token error”} 【定位】：大概可以定位到是我的url问题，所以我后续又进行了一些操作，导致我对这个问题描述：比较离谱 【后续】：
> 4. 我在我的linux机器上采用同一个url，访问token error
> 5. 我在我的Windows电脑上采用同一个url，curl返回竟然是正确的？！
> 6. 不信邪，所以我在我的个人手机上采用同一个手机又进行了一次配置拉取，也是正常的。
>    【问】：同一个链接是否还会对设备进行上限设置？

感谢反馈并支持，这类现象并不会对设备进行上限限制，检查你的机场URL是否为标准的clash格式，一般都是https://xxx.xxx/api/base64加密后的字符串，如果不是，你可以手动把config.yml配置文件放到clash for linux的数据目录
